### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by nibanks** [microsoft/action-publish-symbols#10]
Hello, I'm trying to migrate from an internal VSO repo to GitHub (currently private), and trying to get symbol server publishing from a GitHub action working. I am currently getting a `404` error code though.

Example internal pipeline run that works: https://mscodehub.visualstudio.com/WindowsXDP/_build/results?buildId=265387&view=logs&j=dd755d80-e2a8-5bc6-1364-e03f69bfc23b&t=79e9e941-3473-58ec-d89d-2e6a82029a75
Example external Action that is failing: https://github.com/microsoft/xdp-for-windows/runs/6442213846?check_suite_focus=true#step:10:9

My usage:

```yml
    - uses: microsoft/action-publish-symbols@v1
      with:
        accountName: nibanks
        symbolServiceUrl: 'https://mscodehub.artifacts.visualstudio.com'
        personalAccessToken: ${{ secrets.AZDO_PAT }}
```

Action output:
```
Run microsoft/action-publish-symbols@v1
Symbol Request Name = microsoft/xdp-for-windows/ci/10/2327846101/1ba201b2-520b-4e7d-fde1-b54928bb438c
Found 29 files
Error: Action failed with error Error: Request failed with status code 404
```

What am I doing wrong? Any help would be greatly appreciated.

cc @thhous-msft

**Comment by nibanks** [comment]
Well, it seems like doing it this way fixed the problem:
```yml
    - uses: microsoft/action-publish-symbols@v1
      with:
        accountName: mscodehub
        symbolServiceUrl: 'https://artifacts.dev.azure.com'
        personalAccessToken: ${{ secrets.AZDO_PAT }}
```
It might be good to update the documentation to be a bit more clean about what `accountName` refers to and provide a couple examples. Thanks!
