### ISSUE TITLE
Not able to use microsoft/action-publish-symbols@v2.1.6

### ISSUE THREAD

**Issue by learnprofile** [microsoft/action-publish-symbols#37]
Not able to use microsoft/action-publish-symbols@v2.1.6 for Github actions.

as tried adding microsoft/action-publish-symbols@v2.1.6 from market place however looks like it is compatible only with AzureDevOps but not with Github.

if i pass it as

```
    - name: Publish Symbols
      uses: microsoft/action-publish-symbols@v2.1.6
      with:
        searchPattern: '**/bin/**/*.pdb'
```
it gives me error as, and you can see it try to go to AzureDevOps artifacts server.

```
Run microsoft/action-publish-symbols@v2.1.6
  with:
    searchPattern: **/bin/**/*.pdb
    symbolServiceUrl: https://artifacts.dev.azure.com
  env:
    BUILD_CONFIGURATION: Release
    SOLUTION: AnalysisEngine/AEDeploy.sln
    NUGET: C:\hostedtoolcache\windows\nuget.exe\5.5.1\x64/nuget.exe
Error: Action failed with error Error: Input required and not supplied: accountName
```

so is there a way to use this for Github actions and upload onto Github artifacts itself?
